AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  paimonganyu-skill

  SAM Template for paimonganyu-skill (KAKAOTALK Chatbot Skill Server)

Parameters:
  Env:
    Type: String
    Default: test
    AllowedValues:
      - test
      - prod
    Description: The stage of this deployment.

Conditions:
  isProd: !Equals
    - !Ref Env
    - prod

Resources:

  BeanstalkBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub eb-${AWS::StackName}-${AWS::AccountId}-${AWS::Region}

#      Policies:
#        - S3ReadPolicy:
#            BucketName: !Sub codebucket-${AWS::StackName}-${AWS::AccountId}-${AWS::Region}

  # PaimonGanyuChatbot
  PaimonGanyuSpringBootApp:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.binchoo.paimonganyu.chatbot.PaimonGanyuLambda::handleRequest
      MemorySize: !If [isProd, 1644, 512]
      Timeout: 60
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserHoyopassTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UserDailyCheckTable
        - DynamoDBReadPolicy:
            TableName: !Ref UserRedeemTable
        - SSMParameterReadPolicy:
            ParameterName: HoyopassPrivateKey
        - SSMParameterReadPolicy:
            ParameterName: HoyopassPublicKey
      Events:
        RestApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
            Auth:
              ApiKeyRequired: true
      Environment:
        Variables:
          PROFILE: !If [isProd, prod, stage]
      AutoPublishAlias: PaimonGanyuChatbot
      ProvisionedConcurrencyConfig:
        Condition: isProd
        ProvisionedConcurrentExecutions: 2
      DeploymentPreference:
        Type: !If [isProd, Canary10Percent10Minutes, AllAtOnce]