package org.binchoo.paimonganyu.hoyopass.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import org.binchoo.paimonganyu.hoyopass.entity.utils.LocalDateTimeStringConverter;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;


@Setter
@Getter
@AllArgsConstructor
@Builder(toBuilder = true)
@DynamoDBTable(tableName = Hoyopass.TABLE_NAME)
public class Hoyopass implements Comparable<Hoyopass> {
    public static final String TABLE_NAME = "hoyopass";

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "userId")
    @DynamoDBAttribute
    private String userId;

    @DynamoDBAttribute
    private String ltuid;

    @DynamoDBAttribute
    private String ltoken;

    @DynamoDBAttribute
    private List<String> uidList; // region to uid string mapping

    @DynamoDBTypeConverted(converter = LocalDateTimeStringConverter.class)
    @DynamoDBAttribute
    private LocalDateTime createAt;

    public Hoyopass() {
        this.initUidList();
        this.createAt = LocalDateTime.now();
    }

    private void initUidList() {
        this.uidList = new ArrayList<>();
    }

    public Hoyopass(String userId, String ltuid, String ltoken, Uid... uids) {
        this();
        for (Uid uid : uids) {
            uidList.add(uid.getUid());
        }
    }

    @Override
    public int compareTo(Hoyopass o) {
        return this.createAt.compareTo(o.getCreateAt());
    }
}
