version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "paimonganyu"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-idkhpdkh78w2"
s3_prefix = "paimonganyu"
region = "ap-northeast-2"
profile = "pgtest"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "Env=\"test\""
