package org.binchoo.paimonganyu.infra.redeem.dynamo.item;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;
import org.binchoo.paimonganyu.infra.utils.LocalDateTimeStringConverter;
import org.binchoo.paimonganyu.redeem.RedeemCode;
import org.binchoo.paimonganyu.redeem.UserRedeem;

import java.time.LocalDateTime;

import static org.binchoo.paimonganyu.infra.redeem.dynamo.item.UserRedeemItem.TABLE_NAME;

/**
 * @author : jbinchoo
 * @since : 2022-04-19
 */
@Setter // required for conversion and unconversion, never remove this.
@Data
@Builder
@AllArgsConstructor
@DynamoDBTable(tableName = TABLE_NAME)
public class UserRedeemItem {

    public static final String TABLE_NAME = "UserRedeem";

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String botUserId;

    @DynamoDBAttribute
    private String uid;

    @DynamoDBAttribute
    private String code;

    @DynamoDBAttribute
    private String reason;

    @DynamoDBConvertedBool(DynamoDBConvertedBool.Format.true_false)
    private boolean done;

    @DynamoDBTypeConverted(converter = LocalDateTimeStringConverter.class)
    private LocalDateTime date;

    public UserRedeemItem() { }

    public static UserRedeem toDomain(UserRedeemItem userRedeemItem) {
        return UserRedeem.builder()
                .botUserId(userRedeemItem.botUserId)
                .uid(userRedeemItem.uid)
                .redeemCode(RedeemCode.of(userRedeemItem.code))
                .done(userRedeemItem.done)
                .reason(userRedeemItem.reason)
                .date(userRedeemItem.date)
                .build();
    }

    public static UserRedeemItem fromDomain(UserRedeem userRedeem) {
        return UserRedeemItem.builder()
                .botUserId(userRedeem.getBotUserId())
                .uid(userRedeem.getUid())
                .code(userRedeem.getRedeemCode().getCode())
                .reason(userRedeem.getReason())
                .done(userRedeem.isDone())
                .date(userRedeem.getDate())
                .build();
    }
}
