version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "paimonganyu-skill"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-idkhpdkh78w2"
s3_prefix = "paimonganyu-skill"
region = "ap-northeast-2"
profile = "pgtest"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Env=\"test\" UseALB=\"False\""
image_repositories = []
disable_rollback = true
