version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "paimonganyu-skill"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1j5078jk7ifir"
s3_prefix = "paimonganyu-skill"
region = "ap-northeast-1"
profile = "pgtest"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Env=\"test\""
image_repositories = []
disable_rollback = true
