package org.binchoo.paimonganyu.infra.redeem.dynamo.item;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;
import org.binchoo.paimonganyu.infra.utils.LocalDateTimeStringConverter;
import org.binchoo.paimonganyu.redeem.RedeemCode;
import org.binchoo.paimonganyu.redeem.UserRedeem;

import java.time.LocalDateTime;

import static org.binchoo.paimonganyu.infra.redeem.dynamo.item.UserRedeemItem.TABLE_NAME;

/**
 * @author : jbinchoo
 * @since : 2022-04-19
 */
@ToString
@Setter // required for conversion and unconversion, never remove this.
@Getter
@Builder
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = TABLE_NAME)
public class UserRedeemItem {

    public static final String TABLE_NAME = "UserRedeem";

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String botUserId;

    @DynamoDBAttribute
    private String uid;

    @DynamoDBAttribute
    private String code;

    @DynamoDBConvertedBool(DynamoDBConvertedBool.Format.true_false)
    private boolean done;

    @DynamoDBTypeConverted(converter = LocalDateTimeStringConverter.class)
    private LocalDateTime createAt;

    public static UserRedeem toDomain(UserRedeemItem userRedeemItem) {
        return new UserRedeem(userRedeemItem.botUserId,
                userRedeemItem.uid, new RedeemCode(userRedeemItem.code), userRedeemItem.done);
    }

    public static UserRedeemItem fromDomain(UserRedeem userRedeem) {
        return UserRedeemItem.builder()
                .botUserId(userRedeem.getBotUserId())
                .uid(userRedeem.getUid())
                .code(userRedeem.getRedeemCode().getCode())
                .done(userRedeem.isDone())
                .build();
    }
}
