package org.binchoo.paimonganyu.dailycheck.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Getter;
import org.binchoo.paimonganyu.awsutils.dynamo.LocalDateTimeStringConverter;

import java.time.LocalDate;
import java.time.LocalDateTime;

@Getter
@DynamoDBTable(tableName="UserDailyCheck")
public class UserDailyCheck {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    String id;

    @DynamoDBIgnore
    String botUserId;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "botUserIdLtuid")
    String botUserIdLtuid;

    @DynamoDBIgnore
    String ltuid;

    @DynamoDBTypeConverted(converter = LocalDateTimeStringConverter.class)
    LocalDateTime timestamp;

    UserDailyCheckResult result;

    public UserDailyCheck(String botUserId, String ltuid, UserDailyCheckResult result) {
        this.botUserId = botUserId;
        this.ltuid = ltuid;
        this.botUserIdLtuid = botUserId + "-" + ltuid;
        this.result = result;
        this.timestamp = LocalDateTime.now();
    }

    public static UserDailyCheck completed(String botUserid, String ltuid) {
        return new UserDailyCheck(botUserid, ltuid, UserDailyCheckResult.COMPLETED);
    }

    public static UserDailyCheck failed(String botUserid, String ltuid) {
        return new UserDailyCheck(botUserid, ltuid, UserDailyCheckResult.FAILED);
    }

    public boolean isDoneOn(LocalDate date) {
        return timestamp.toLocalDate().isEqual(date);
    }
}
