version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "paimonganyu"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-11wakjp33mgsw"
s3_prefix = "paimonganyu"
region = "ap-northeast-1"
profile = "serverless"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "Env=\"test\""
